/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gdev.timetable.dialogs;

import com.gdev.timetable.db.DbManager;
import com.gdev.timetable.helper.AutoCompleteData;
import com.gdev.timetable.helper.MessageDisplay;
import com.gdev.timetable.utility.Utility;
import com.gdev.timetable.model.ConfigDetail;
import com.gdev.timetable.model.IdName;
import com.gdev.timetable.model.Result;
import java.util.Vector;
import java.util.stream.IntStream;

/**
 *
 * @author Admin
 */
public class AddConfigDialog extends javax.swing.JDialog {

    private static AddConfigDialog mInstance;

    /**
     * Creates new form AddConfigDialog
     */
    public AddConfigDialog() {
        super(Utility.getDefault().getParent(), false);
        initComponents();
        setLocation(Utility.getCenterLocation(getSize()));
        Utility.addDefaultKeyListener(btnSubmit, btnClose);
        setTitle("Add Configuration");
    }

    public static AddConfigDialog getDefault() {
        if (mInstance == null) {
            mInstance = new AddConfigDialog();
        }
        return mInstance;
    }

    private void clear() {
        combDep.setSelectedIndex(0);
        combBranch.setSelectedIndex(0);
        combSem.setSelectedIndex(0);
        txtTotLec.setText("6");
        txtTotalDay.setText("5");
        txtBreakAfter.setText("0");
        txtMaxGen.setText("2000");
        chkUpdateDup.setSelected(false);
    }

    public void init() {
        combDep.setData(AutoCompleteData.getDefault().getDepartmentListner(true));
        combBranch.setData(AutoCompleteData.getDefault().getBranchListner(true));
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combDep = new com.gdev.timetable.helper.AutoCompleteComboBox();
        combBranch = new com.gdev.timetable.helper.AutoCompleteComboBox();
        combSem = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTotLec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalDay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBreakAfter = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMaxGen = new javax.swing.JTextField();
        chkUpdateDup = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel1.text")); // NOI18N

        combSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        org.openide.awt.Mnemonics.setLocalizedText(btnSubmit, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.btnSubmit.text")); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnClose, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.btnClose.text")); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel4.text")); // NOI18N

        txtTotLec.setText(org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.txtTotLec.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel5.text")); // NOI18N

        txtTotalDay.setText(org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.txtTotalDay.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel6.text")); // NOI18N

        txtBreakAfter.setText(org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.txtBreakAfter.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.jLabel7.text")); // NOI18N

        txtMaxGen.setBackground(new java.awt.Color(204, 204, 204));
        txtMaxGen.setText(org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.txtMaxGen.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chkUpdateDup, org.openide.util.NbBundle.getMessage(AddConfigDialog.class, "AddConfigDialog.chkUpdateDup.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBreakAfter, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combDep, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(combSem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(combBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotLec, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalDay))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaxGen))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkUpdateDup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(combDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtTotLec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtTotalDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaxGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBreakAfter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose)
                        .addComponent(btnSubmit))
                    .addComponent(chkUpdateDup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if (combDep.getSelectedItem() == null || ((IdName) combDep.getSelectedItem()).getId() == 0) {
            MessageDisplay.showErrorDialog(this, "Please Select valid Department");
            return;
        }
        if (combBranch.getSelectedItem() == null || ((IdName) combBranch.getSelectedItem()).getId() == 0) {
            MessageDisplay.showErrorDialog(this, "Please Select valid Branch");
            return;
        }
        if (Utility.getLongValue(txtTotLec.getText()) == 0) {
            MessageDisplay.showErrorDialog(this, "Invalid Total Lectures");
            return;
        }
        if (Utility.getLongValue(txtTotalDay.getText()) == 0) {
            MessageDisplay.showErrorDialog(this, "Invalid Total days");
            return;
        }
        if (Utility.getIntValue(txtMaxGen.getText()) < 500) {
            MessageDisplay.showErrorDialog(this, "Invalid Max Generations (Max Generation can't be less then 500)");
            return;
        }
        long dep = ((IdName) combDep.getSelectedItem()).getId();
        long branch = ((IdName) combBranch.getSelectedItem()).getId();
        long sem = combSem.getSelectedIndex();
        Vector<ConfigDetail> config = new Vector();

        if (dep == -1) {
            Vector<IdName> depData = DbManager.getDefault().getDepartments();
            depData.forEach(d -> {
                CheckBranches(branch, sem, config, d);
            });
        } else {
            CheckBranches(branch, sem, config, ((IdName) combDep.getSelectedItem()));
        }

        Result r = DbManager.getDefault().addConfig(config, chkUpdateDup.isSelected());
          if (r.isSuccess()) {
            MessageDisplay.showSuccessDialog(null, "Configuration Added Succesfully", "Success");
            clear();
        } else {
            MessageDisplay.showErrorDialog(null, r.getMessage());
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void CheckBranches(long branch, long sem, Vector<ConfigDetail> config, IdName d) {
        if (branch == -1) {
            Vector<IdName> BranchData = DbManager.getDefault().getBranchs();
            BranchData.forEach(b -> {
                if (sem == 0) {
                    IntStream.range(1, 9).forEach(s -> {
                        config.add(createConfig(d.getId(), b.getId(), s));
                    });
                } else {
                    config.add(createConfig(d.getId(), b.getId(), sem));
                }
            });
        } else {
            if (sem == 0) {
                IntStream.range(1, 9).forEach(s -> {
                    config.add(createConfig(d.getId(), branch, s));
                });
            } else {
                config.add(createConfig(d.getId(), branch, sem));
            }
        }
    }

    private ConfigDetail createConfig(long dep, long branch, long sem) {
        ConfigDetail detail = new ConfigDetail();
        detail.setDep_id(dep);
        detail.setBranch_id(branch);
        detail.setSem(sem);
        detail.setBreak_after(Utility.getLongValue(txtBreakAfter.getText()));
        detail.setTotal_day(Utility.getLongValue(txtTotalDay.getText()));
        detail.setTotal_lec(Utility.getLongValue(txtTotLec.getText()));
        detail.setMax_generations(Utility.getIntValue(txtMaxGen.getText()));
        return detail;
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        mInstance = null;
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkUpdateDup;
    private com.gdev.timetable.helper.AutoCompleteComboBox combBranch;
    private com.gdev.timetable.helper.AutoCompleteComboBox combDep;
    private javax.swing.JComboBox combSem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBreakAfter;
    private javax.swing.JTextField txtMaxGen;
    private javax.swing.JTextField txtTotLec;
    private javax.swing.JTextField txtTotalDay;
    // End of variables declaration//GEN-END:variables

}
