/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gdev.timetable.dialogs;

import com.gdev.timetable.db.DbManager;
import com.gdev.timetable.helper.AutoCompleteData;
import com.gdev.timetable.helper.MessageDisplay;
import com.gdev.timetable.helper.Utility;
import com.gdev.timetable.model.IdName;
import com.gdev.timetable.model.Result;
import com.gdev.timetable.model.SubjectDetail;
import java.util.Vector;
import java.util.function.Predicate;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gurwinder Singh
 */
public class CreateSubject extends javax.swing.JDialog {

    private static CreateSubject mInsatnce;
    private Vector dataVector;
    private boolean modify = false;

    /**
     * Creates new form CreateSubject
     */
    public CreateSubject() {
        super(Utility.getDefault().getParent(), false);
        initComponents();
        setLocation(Utility.getCenterLocation(getSize()));
        Utility.addDefaultKeyListener(btnSave, btnClose);
        dataVector = new Vector();
        inputTable.setModel(new CustomTableModel());
        setTitle("Create Subject");
    }

    public static CreateSubject getDefault() {
        if (mInsatnce == null) {
            mInsatnce = new CreateSubject();
        }
        return mInsatnce;
    }

    public void init() {
        combBranch.setData(AutoCompleteData.getDefault().getBranchListner());
        combDep.setData(AutoCompleteData.getDefault().getDepartmentListner());

        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        combBranch = new com.gdev.timetable.helper.AutoCompleteComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combDep = new com.gdev.timetable.helper.AutoCompleteComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSubId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAlias = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combType = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        combSem = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel3.text")); // NOI18N

        txtName.setText(org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.txtName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel4.text")); // NOI18N

        txtSubId.setText(org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.txtSubId.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel5.text")); // NOI18N

        txtAlias.setText(org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.txtAlias.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel6.text")); // NOI18N

        combType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Theory", "Practical" }));

        org.openide.awt.Mnemonics.setLocalizedText(btnDelete, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.btnDelete.text")); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnAdd, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.btnAdd.text")); // NOI18N
        btnAdd.setNextFocusableComponent(txtName);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        inputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(inputTable);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.jLabel7.text")); // NOI18N

        combSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        org.openide.awt.Mnemonics.setLocalizedText(btnSave, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.btnSave.text")); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnClose, org.openide.util.NbBundle.getMessage(CreateSubject.class, "CreateSubject.btnClose.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(combSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combType, 0, 82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(20, 20, 20)
                                .addComponent(btnClose)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(combDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(combSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSubId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(combType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (txtName.getText().trim().isEmpty()) {
            MessageDisplay.showErrorDialog(this, "Please Enter Subject Name");
            txtName.requestFocus();
            return;
        }
        if (txtSubId.getText().trim().isEmpty()) {
            MessageDisplay.showErrorDialog(this, "Please Enter Subject Id");
            txtSubId.requestFocus();
            return;
        }
        SubjectDetail detail = new SubjectDetail();
        detail.setName(txtName.getText());
        detail.setAlias(txtAlias.getText());
        detail.setSub_id(txtSubId.getText());
        detail.setType(combType.getSelectedItem().toString());
        if (dataVector.stream().anyMatch((Object x1) -> {
            SubjectDetail row = (SubjectDetail) x1;
            return row.getSub_id().equalsIgnoreCase(detail.getSub_id())
                    || row.getName().equalsIgnoreCase(detail.getName())
                    || row.getAlias().equalsIgnoreCase(detail.getAlias());
        })) {
            MessageDisplay.showErrorDialog(this, "Duplicate Record");
            return;
        }
        dataVector.add(detail);
        inputTable.tableChanged(null);
        txtName.setText("");
        txtAlias.setText("");
        txtSubId.setText("");
        combType.setSelectedIndex(0);

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (dataVector.isEmpty()) {
            MessageDisplay.showErrorDialog(this, "Please Enter data");
            return;
        }
        if (combDep.getSelectedItem() == null || ((IdName) combDep.getSelectedItem()).getId() == 0) {
            MessageDisplay.showErrorDialog(this, "Please Select valid Department");

            return;
        }
        if (combBranch.getSelectedItem() == null || ((IdName) combBranch.getSelectedItem()).getId() == 0) {
            MessageDisplay.showErrorDialog(this, "Please Select valid Branch");

            return;
        }

        // know how to cast x to SubjectDetail before foreach in stream?
        // i'm want replace   SubjectDetail element = (SubjectDetail) x; 
        // how  only use x. (If you know correct it and send pull request)
        //
//        dataVector.forEach(x ->{
//         SubjectDetail element = (SubjectDetail) x;
//         //
//        });
        for (int i = 0; i < dataVector.size(); i++) {
            SubjectDetail element = (SubjectDetail) dataVector.elementAt(i);
            element.setDep_id(((IdName) combDep.getSelectedItem()).getId());
            element.setBranch_id(((IdName) combBranch.getSelectedItem()).getId());
            element.setSem(combSem.getSelectedIndex() + 1);
        }
        Result r = null;
        if (modify) {
//            detail.setId(id);
//            r = DbManager.getDefault().modifyTeacher(detail);
        } else {
            r = DbManager.getDefault().addSubject(dataVector);
        }
        if (r.isSuccess()) {
            MessageDisplay.showSuccessDialog(null, "Subjects Added Succesfully", "Success");
            clear();
        } else {
            MessageDisplay.showErrorDialog(null, r.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (inputTable.getSelectedRow() != -1) {
            dataVector.remove(inputTable.getSelectedRow());
            inputTable.tableChanged(null);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private com.gdev.timetable.helper.AutoCompleteComboBox combBranch;
    private com.gdev.timetable.helper.AutoCompleteComboBox combDep;
    private javax.swing.JComboBox combSem;
    private javax.swing.JComboBox combType;
    private javax.swing.JTable inputTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSubId;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        combDep.setSelectedItem(null);
        combBranch.setSelectedItem(null);
        combSem.setSelectedIndex(0);
        combType.setSelectedIndex(0);
        txtName.setText("");
        txtAlias.setText("");
        txtSubId.setText("");
        dataVector.clear();
//        combDep.getInputField().requestFocus();
    }

    class CustomTableModel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return dataVector.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public String getColumnName(int column) {
            String[] name = {"S.No", "Name", "Alias", "Id", "Type"};
            return name[column];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            SubjectDetail row = (SubjectDetail) dataVector.elementAt(rowIndex);
            switch (columnIndex) {
                case 0:
                    return rowIndex + 1;
                case 1:
                    return row.getName();
                case 2:
                    return row.getAlias();
                case 3:
                    return row.getSub_id();
                case 4:
                    return row.getType();

            }
            return null;
        }

    }
}
